### ISSUE TITLE
Premier rendu

### ISSUE THREAD

**Issue by axelbertrand** [PolytechLyon/2019-isi3-graph-haidari_bertrand#1]

**Comment by Slashgear** [comment]
- ⚠️ On ne commit pas les fichier `out` dans un dépot git

- Seriez vous m'expliquer la différence entre un Set et une List en Java ? A quelles endroits devriez vous utilisez le type Set au lieu de la List?

**Comment by axelbertrand** [comment]
Bonjour, nous avons supprimé le dossier `out`.

Un Set est une collection qui stocke des objets distincts (donc pas de doublon) et pas toujours ordonnés alors qu'une List stocke des objets ordonnés et peut accepter les doublons.
